name: CI/CD Proyecto4 by Klevert Herrera
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          
      - name: Build JAR with Maven
        run: mvn package
        
      - uses: azure/docker-login@v1
        with:
          login-server: acrbootcamp49.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build Docker image
        run: docker build -t discovery-service .

      - name: tag docker image
        run: docker tag discovery-service:latest acrbootcamp49.azurecr.io/discovery-service:latest


      - name: Push Docker image to ACR
        run: docker push acrbootcamp49.azurecr.io/discovery-service:latest
