name: CI/CD Proyecto4 by Klevert Herrera
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonando repositorio
      uses: actions/checkout@v2

    - name: Configurando JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Limpiando y luego generando .JAR
      run: mvn clean package

    - name: Estableciendo docker
      uses: docker/setup-buildx-action@v1

    - name: Creando imagen y haciendo push a ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
      env:
        DOCKER_BUILDKIT: 1
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        docker buildx build --progress=plain --tag ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_REPOSITORY }}:$IMAGE_TAG --file Dockerfile .
        docker push ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_REPOSITORY }}:$IMAGE_TAG
