name: CI/CD Proyecto4 by Klevert Herrera
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          
      - name: Build JAR with Maven
        run: mvn package
        
      - name: Log into registry ${{ secrets.ACR_REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Push Docker Image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker buildx build --progress=plain --tag my-docker-image:$IMAGE_TAG --file Dockerfile --output type=docker .
          docker push my-docker-image:$IMAGE_TAG
